project:
  type: website
  output-dir: docs

website:
  title: "4ms-winter-school"
  navbar:
    left:
      - href: https://winterschool4ms.dpg.unipd.it/
        text: WS main website
        target: _blank
    tools:
      - icon: github
        href: https://github.com/psicostat/4ms-winter-school
        text: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



