project:
  type: website
  output-dir: docs

website:
  title: "4ms-winter-school"
  navbar:
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        href: https://github.com/psicostat/4ms-winter-school
        text: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



