---
title: "4ms-winter-school"
bibliography: "https://raw.githubusercontent.com/filippogambarota/bib-database/main/references.bib"
csl: files/apa-cv.csl
include-in-header: files/header.html
suppress-bibliography: true
---

<center>
{{< qrcode https://github.com/psicostat/4ms-winter-school >}}
</center>

## Slides

***Monday***

Dorothy Bishop - How our Brains Make it Difficult to Think Like a Scientist / Understanding how cognitive biases affect research [[pdf]](slides/bishop-2025_WinterSch.pdf){target=_blank}

Daniel Lakens - Which research is valuable enough to do well? [[pdf]](slides/Lakens_4M_17-2-2025_research_worth_doing.pdf){target=_blank}

Daniel Lakens - Concerns about Replicability, Theorizing, Applicability, Generalizability, and Methodology across Two Crises in Psychology [[pdf]](slides/Lakens_4M_17-2-2025_two_crises.pdf){target=_blank}

Filippo Gambarota - Open Science Starter Pack [[pdf]](slides/open-science-starter-pack.pdf){target=_blank}

***Tuesday***

(*Interview with researcher [[video]](https://www.youtube.com/watch?v=ZaNtz76dNSI){target=_blank>}*)

Daniel Lakens - The benefits of preregistration and registered reports [[pdf]](slides/Lakens-4M-18-2-2025-Preregistration.pdf){target=_blank}

Jessica Flake - Measurement not schmeasurement [[pdf]](slides/Flake-Measurement-not-Schmeasurement-WS.pdf){target=_blank}

Jessica Flake - Measurement and the next generation of open science reform [[pdf]](slides/Flake-Next-Generation-Methodological-Reform.pdf){target=_blank}

Jessica Flake - Materials for students [[zip]](slides/Flake-Materials-for-Students.zip) - Additional <a href="https://journals.sagepub.com/doi/full/10.1037/a0025704?casa_token=BoBrPoMWDLUAAAAA%3ANVr0QjH8E8pdET0XITdv_L70euQNUqSN6mBkc8UNWuiJWp6K90vdS016Z4m_iSAz7dy_WetWE-ViDQ" target=_blank>article</a> [[pdf]](papers/Gehlbach-and-Brinkworth-2011-Measure-twice.pdf){target=_blank}

***Wednesday***

Ettore Ambrosini - From Noise to Insight: Improving neuroimaging measurement for credible and reproducible neuroscience [[pdf]](slides/4M_Ettore_ToShare_WS.pdf){target=_blank} - see also the [recording](https://mediaspace.unipd.it/media/4M_EttoreAmbrosini/1_q6tva30n){target=_blank}

Lisa DeBruine - Big Team Setup [[link]](https://debruine.github.io/big-team-setup/){target=_blank}

Lisa DeBruine - Coding Club: Creating an R Package [[link]](https://psyteachr.github.io/intro-r-pkgs/){target=_blank} - see also [demopkg](https://psyteachr.github.io/demopkg/){target=_blank}

***Thursday***

Ulrich Schimmack - Theoretical Factor Analysis [[pdf]](slides/Schimmack-Padua-Winter-School-25.pdf){target=_blank}

Giulia Calignano - Multilab and Multiverse: from preprocessing to data analysis [[pdf]](slides/4Ms_Multiverse_calignano.pdf){target=_blank}

Giulia Calignano - additional materials: OSF repo [[link]](https://osf.io/bhuxf/){target=_blank}

Livio Finos - PIMA: Post-selection Inference in Multiverse
Analysis [[pdf]](slides/Finos-PIMA-ws.pdf){target=_blank}

Livio Finos - additional materials: PIMA dataset [[html]](slides/pima_dataset.html){target=_blank} / GitHub repo [[link]](https://github.com/livioivil/pima){target=_blank}

***Friday***

Massimo Grassi - Do musicians have better short-term memory than nonmusicians? A multi-lab study [[pdf]](slides/Grassi-MusiciansMultilab-WS1.pdf){target=_blank}

Filippo Gambarota - A multi-lab study: Power analysis and data management [[pdf]](slides/multilab-grassi-power.pdf){target=_blank}

***Follow up***

Ettore Ambrosini - 2^nd^ part / "extra" lesson on From Noise to Insight: Improving neuroimaging measurement for credible and reproducible neuroscience (2025-02-26) [[recording]](https://mediaspace.unipd.it/media/4M_EttoreAmbrosini_Round2/1_cc4hw7qr){target=_blank}


## Group Activities

### Measurement

#### Group 1

@Elson2023-iw [[pdf]](papers/Elson%20et%20al.%202023%20-%20Psychological%20measures%20aren't%20toothbrushes.pdf){target=_blank} — In addition: Select a psychological construct (e.g., cognitive load, word recognition, intrinsic motivation), and compare how five published studies measured it; consider differences in operationalization, scoring, and standardization, and suggest the impact that this variability may have on replicability.

- Zofia Dobrowolska 
- Louie Lei	Wang
- Stefano Dalla Bona
- Giulia Moncalieri
- Rocío	Vizcaíno-Cuenca
- Michela Forcella

#### Group 2

@Stapleton2016-el [[pdf]](papers/Stapleton%20et%20al.%202016%20-%20Construct%20meaning%20in%20multilevel%20settings.pdf){target=_blank}

- Lu Zhang
- Yara Alnajjar
- Lucrezia Guiotto Nai Fovino
- Caroline Böhm
- Cemre	Çınar

### Meta-Research

#### Group 1

@Ulrich2020-rk [[pdf]](papers/Ulrich%20and%20Miller%202020%20-%20Questionable%20research%20practices%20may%20have%20little%20effect%20on%20replicability.pdf){target=_blank}

- Rrita Bajraktari
- Giulia Paludo
- Fabrizio Visconti
- Francisco Miguel Soler Martínez

#### Group 2

@Fried2020-oe [[pdf]](papers/Fried 2020 - Theories and models - What they are, what they are for, and what they are about.pdf){target=_blank}

- Raphael Merz
- Ruben Lamers James
- Elena Rinallo
- Andreas Voldstad
- Benjamin Kunc

### Multi-Lab

@Byers-Heinlein2020-pa [[pdf]](papers/Byers-Heinlein%20et%20al.%202020%20-%20Building%20a%20collaborative%20Psychological%20Science%20-%20Lessons%20learned%20from%20ManyBabies%201.pdf){target=_blank}

#### Group 1

- Stefano Ioannucci
- Yashiv Seetahul
- Sana Rehmat
- Giulia Brizzi

### Multiverse

#### Group 1

@Steegen2016-gx [[pdf]](papers/Steegen%20et%20al.%202016%20-%20Increasing%20Transparency%20Through%20a%20Multiverse%20Analysis.pdf){target=_blank}

- Marco Roccato
- Isabella Mariani Wigley
- Miłosz Kalinowski
- Clara Alameda

#### Group 2

@Del_Giudice2021-nm [[pdf]](papers/Del Giudice and Gangestad 2021 - A traveler’s guide to the multiverse, pitfalls, and a framework for the evaluation of analytic decisions.pdf){target=_blank}

- Marco Badioli
- Ettore Napoli
- Marta Paź
- Victor Auger
- Alice Tupinier
 
